#!/bin/bash

echo "removing all files created when running the test suite"

rm teufel_bunch_start.sdds
rm rad_push_log.sdds
rm matching.sdds
rm fel1d*
rm fel-modulation_*
rm tests/DiffractionScreenWithFields.h5

