#!/bin/bash

num=0
red='\033[1;31m'
green='\033[1;32m'
nc='\033[0m'

cd tests

./teufel.integrate_field; rc=$?
num=$(($num + $rc))

echo ''
echo '==============================================================================='
echo ''

./teufel.bunch; rc=$?
num=$(($num + $rc))

echo ''
echo '==============================================================================='
echo ''

./teufel.magnet; rc=$?
num=$(($num + $rc))

echo ''
echo '==============================================================================='
echo ''

./teufel.undulator; rc=$?
num=$(($num + $rc))

echo ''
echo '==============================================================================='
echo ''

./teufel.loop; rc=$?
num=$(($num + $rc))

echo ''
echo '==============================================================================='
echo ''

./teufel.EcrossB; rc=$?
num=$(($num + $rc))

echo ''
echo '==============================================================================='
echo ''

if [ $num = "0" ]
then
    echo -e "$green no errors - all tests passed.$nc"
else
    echo -e "$red there were errors - some test failed!$nc"
fi

