/*=========================================================================
 * 
 *  Program:   TEUFEL - THz Emission from Undulators and Free-Electron Lasers
 * 
 *  Copyright (c) 2017 U. Lehnert
 * 
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * =========================================================================*/

#pragma once

#include "pugixml.hpp"
#include "vector.h"
#include "fields.h"
#include "beam.h"
#include "parser.h"
#include <vector>

/*!
 * \class CSR
 * \brief An electromagnetic field created by and interacting with the beam
 * @author Ulf Lehnert
 * @date 23.12.2025
 * 
 * This is an electromagnetic field that is generated by a moving particle beam.
 * The beam is sliced along its (average) direction of motion into N slices
 * each containing approximately the same amount of charge.
 *
 * The slice properties (position, momentum, acceleration, length, rms radius)
 * are stored for evey tracking step.
 * The slices propagate along with the motion of the beam and are assumed
 * to have constant properties during one tracking step.
 */
class CSR : public InteractionField
{

public:

    /*! All data stored for a single slice of the beam.
     *  Position, momentum and acceleration of all slices are independent.
     *  Slice.length refers to the average momentum direction of the beam
     *  which is defined per Snapshot.
     */
    struct Slice {
        double charge;
        Vector position;
        Vector momentum;
        Vector accel;
        double length;
        double radius;
    };
    
    /*! All data stored for a complete snapshot of the history
     *  of the beam at a given point in time during tracking.
     *
     *  The position and momentum define a plane through the center
     *  of the bunch perpendicular to its direction of motion.
     *  This plane is the reference for the longitudinal particle position
     *  used for slicing the bunch and computing arrival times.
     *  Slice.length is determined perpendicular to this plane.
     */
    struct Snapshot {
        double tracking_time;
        Vector central_position;
        Vector central_momentum;
        std::vector<Slice> slices;
    };
     
    /*! The default contructor just calls the default constructor of the base class
     *  and initalizes all variables with sane values. This will not yet produce any fields.
     */
    CSR();

    /*! This constructor takes the information from an XML node
     *  describing the slicing properties. It will throw exceptions
     *  if necessary information is missing or cannot be interpreted.
     * 
     *  A reference to the input parser must be provided as it is
     *  necessary to run the input through the calculator.
     */
    CSR(
        const pugi::xml_node node,
        InputParser *parser
        );

    /*! All derived classes from GeneralField must provide a destructor.
     *  This one just cleans up the stored history.
     */
    virtual ~CSR();

    /*! Do all necessary initializations before update() can be called.
     *  The reference to the beam which is the source of the interaction fields is given here.
     *  init() stores references to all particles forming the beam
     *  so CSR objects can access the coordinates and particle properties.
     */
    virtual void init(Beam *beam);

    /*! Subdivide the beam into a number of slices and store the slice data
     *  for logging and future field computations.
     *  After the call the fields can be used for tracking or computing observations.
     *
     *  This method must be called in a leap-frog sequence interleaved with
     *  the tracking steps of the beam.
     *  In the tracking loop update() is called before the tracking step is executed.
     *  The first time update() is called just the initialized beam is available.
     *  Initalizing the tracking computes the fields.
     */
    virtual void update(double tracking_time);
    
    /*!
     * The electromagnetic field at a given time and point in space.
     * 
     * The coordinates [m] and the time [s] refer to the laboratory (rest) frame.
     * The field is returned as a tuple of electric field [V/m] and
     * magnetic field [T] vectors.
     */
    virtual ElMagField Field(double t, Vector X);

    /*! Write stored field data to file if requested (do nothing otherwise).
     *  This will be called once after the tracking is finished.
     */
    virtual void write_output();

private:

    //! the beam which is the field source
    Beam *source_beam;

    //! flag for initialization and allocation of the field map memory.
    bool is_initialized;
    
    //! number of slices stored for every step
    size_t numSlices;
    
    //! the storage for the complete history of the beam
    std::vector<Snapshot *> history;
    
    //! whether to create a field output file
    bool createOutput;
    
    //! the output file name
    const char* FileName;

};

