/*=========================================================================
 * 
 *  Program:   TEUFEL - THz Emission from Undulators and Free-Electron Lasers
 * 
 *  Copyright (c) 2017 U. Lehnert
 * 
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * =========================================================================*/

#pragma once

#include "pugixml.hpp"
#include "vector.h"
#include "fields.h"
#include "beam.h"
#include "parser.h"
#include <vector>

/*!
 * \class CSR
 * \brief An electromagnetic field created by and interacting with the beam
 * @author Ulf Lehnert
 * @date 23.12.2025
 * 
 * This is an electromagnetic field that is generated by a moving particle beam.
 * The beam is sliced along its (average) direction of motion into N slices
 * each containing approximately the same amount of charge.
 *
 * The slice properties (position, momentum, acceleration, length, rms radius)
 * are stored for evey tracking step.
 * The slices propagate along with the motion of the beam and are assumed
 * to have constant properties during one tracking step.
 */
class CSR : public InteractionField
{

public:

    /*! All data stored for a single slice of the beam.
     */
    struct Slice {
        double charge;
        Vector position;
        Vector momentum;
        Vector accel;
        double length;
        double radius;
    };

    /*! The default contructor just calls the default constructor of the base class
     *  and initalizes all variables with sane values. This will not yet produce any fields.
     */
    CSR();

    /*! This constructor takes the information from an XML node
     *  describing the slicing properties. It will throw exceptions
     *  if necessary information is missing or cannot be interpreted.
     * 
     *  A reference to the input parser must be provided as it is
     *  necessary to run the input through the calculator.
     */
    CSR(
        const pugi::xml_node node,
        InputParser *parser
        );

    /*! All derived classes from GeneralField must provide a destructor */
    virtual ~CSR();

    /*! Do all necessary initializations before update() can be called.
     *  Allocate memiry for the field map.
     */
    virtual void init();

    /*! Compute the interaction field for the current state of the beam
     *  given by the tracking_time. If the last stored trajectory point
     *  deviates by more than a fraction (presently 0.5) of a time_step
     *  an Exception is thrown. The field map is then valid for one tracking_time_step.
     *
     *  For computation of the field map all particle positions are
     *  shifted to the center positions of the grid cell they reside in.
     *  The field is computed on the grid nodes and then interpolated for tracking.
     *  This prevents outliers resulting from computing fields too close
     *  to a particle.
     *  TODO: This shifting does not remove the artifacts - 
     *  those just occur at different locations.
     *
     *  After the call the fields can be used for tracking within one time_step.
     *  It is assumed that the field map moves along with the particle beam
     *  So the relative positions of a particle within the field map undergo
     *  negligible changes during one tracking step.
     *  This method must be called in a leap-frog sequence interleaved with
     *  the tracking steps of the beam.
     *
     *  Every step_Output number of steps (including the first call)
     *  the computed grid is stored for later writing to a log file.
     */
    virtual void update(Beam *beam, double tracking_time);
    
    /*!
     * The electromagnetic field at a given time and point in space.
     * The time must be within a time step from the current time of the interaction field.
     * 
     * The requested position is projected into the grid plane.
     * The field is reported  with a constant value for out-off-plane positions.
     * If the requested position is projected outside the grid
     * an exception is thrown.
     * 
     * The coordinates [m] and the time [s] refer to the laboratory (rest) frame.
     * The field is returned as a tuple of electric field [V/m] and
     * magnetic field [T] vectors.
     */
    virtual ElMagField Field(double t, Vector X);

    /*! Write stored field data to file if requested (do nothing otherwise).
     *  This will be called after the tracking is finished.
     */
    virtual void write_output();

private:

    //! flag for initialization and allocation of the field map memory.
    bool is_initialized;
    
    //! number of slices
    int  N_slices;
    
    //! the storage for the complete history of the beam
    std::vector<Slice *> history;
    
    //! whether to create a field output file
    bool createOutput;
    
    //! the output file name
    const char* FileName;

};

