/*=========================================================================
 * 
 *  Program:   TEUFEL - THz Emission from Undulators and Free-Electron Lasers
 * 
 *  Copyright (c) 2017 U. Lehnert
 * 
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * =========================================================================*/

#pragma once

#include <stdio.h>
#include <stdlib.h>
#include <iostream>
#include <vector>

#include "beam.h"
#include "bunch.h"
#include "global.h"
#include "fields.h"
#include "vector.h"

/*! Observers can record fields from different sources
*/
enum RadSource { LatticeObservation, BeamObservation };


/*!
 * \class Observer
 * \brief An general observer of field generated by tracked particles.
 * @author Ulf Lehnert
 * @date 17.5.2018
 * 
 * This class is intended to be a template for all electromagnetic fields
 * handled in this software. Any field derived from this class can be used
 * for tracking particles. It is purely virtual - no implementation is provided.
 */
class Observer
{

public:

    /*! Default constructor with no functionality. */
    Observer() {};

    /*!
     * The destructor must be overridden by derived classes.
     */
    virtual ~Observer() {};
    
    /*!
     *  Integrate the observed fields along the tracked trajectories.
     *  This is a purely virtual method that must be overwritten by derived objects.
     *  It is defined for Beam(), Bunch() and Lattice() as field sources.
     */
    virtual void integrate(Beam *src) = 0;
    virtual void integrate(Bunch *src) = 0;
    virtual void integrate(Lattice *src) = 0;

    /*! The method gives the size of the buffer necessary to store
     *  the complete field information as a number of doubles (not bytes!).
     *  This is a purely virtual method that must be overwritten by derived objects.
     */
    virtual std::size_t getBufferSize() = 0;
    
    /*! Return all field values in a newly allocated buffer.
     *  Memory for the buffer is allocated by this method and must be freed
     *  by the caller. Returns a pointer to the allocated memory.
     *  An exception is thrown if the alloaction of the buffer fails.
     *  This is a purely virtual method that must be overwritten by derived objects.
     */
    virtual double* getBuffer() = 0;

    /*! Set all field values from a given allocated buffer.
     *  The count value gives the size of the buffer as a number of doubles.
     *  An exception is thrown if it doesn't match the actual field size.
     *  This is a purely virtual method that must be overwritten by derived objects.
     */
    virtual void fromBuffer(double *buffer, std::size_t size) = 0;

    /*!
     *  Generate whatever output the special observer has to deliver.
     *  This is a purely virtual method that must be overwritten by derived objects.
     */
    virtual void generateOutput() = 0;

    //! set the source of the fiels to be recorded
    virtual void setSource(RadSource s) = 0;
    
    /*! report the source of the fiels to be recorded
     *  if not overridden this is the beam
     */
    virtual RadSource getSource() = 0;

protected :

    RadSource source;

};

