/* config.h.  Generated by configure.  */
#if defined(_WIN32)
#if !defined(__MINGW32__)
#if _MSC_VER <= 1600
#define isnan _isnan
#endif
#endif
#define copysign _copysign
#define rint (int)
#define M_PI 3.14159265358979323846
#define NO_TIMER
#endif
#if defined(NO_COPYSIGN)
#define copysign(a, b) ((b >= 0.0) ? fabs(a) : -fabs(a))
#endif
